%% Import data from text file.
% Script for importing data from the following text file:
%
%    /home/filipe/sensor-luva/matlab dh/amostragem_teste.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2021/11/14 01:25:01

%% Initialize variables.
filename = '/home/filipe/sensor-luva/matlab dh/amostragem_teste.csv';
delimiter = ',';

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column23: double (%f)
%   column24: double (%f)
%	column25: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'TextType', 'string',  'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
the = dataArray{:, 1};
phi_metacarpa = dataArray{:, 2};
thetaproximal = dataArray{:, 3};
proximalphi = dataArray{:, 4};
pressure = dataArray{:, 5};
reftheta = dataArray{:, 6};
refphi = dataArray{:, 7};
VarName25 = dataArray{:, 8};


%% Clear temporary variables
clearvars filename delimiter formatSpec fileID dataArray ans;